name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    timeout-minutes: 3
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm typecheck
      - name: Start pg
        run: docker-compose -f docker-compose.yml up -d
      - name: Run indexer
        env:
          ENABLED_CHAINS: base
          MAINNET_RPC: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
          BASE_RPC: https://base-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
        run: pnpm dev --disable-ui &

      - name: Wait for healthy status
        run: pnpx wait-on http://localhost:42069/health

      - name: Can codegen
        run: pnpm codegen
