name: CI

on:
  push:
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Typecheck
        run: bun typecheck
      - name: Start pg
        run: docker-compose -f docker-compose.yml up -d
      - name: Run indexer
        env:
          PONDER_RPC_URL_1: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
          PONDER_RPC_URL_84532: https://base-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
        run: bun start &

      - name: wait for indexer to start
        run: bunx wait-on http://localhost:3000/health
